'use strict';
const assert=require('node:assert/strict'),s=require('./nguonc-source'),{parseRequest}=require('./rophim-source');
const category={country:{group:{name:'Quốc gia'},list:[{name:'Việt Nam'}]},year:{group:{name:'Năm'},list:[{name:'2025'}]},type:{group:{name:'Định dạng'},list:[{name:'Phim lẻ'}]}};
const movie={slug:'fixture',name:'Fixture',original_name:'Fixture',category,episodes:[{server_name:'Vietsub',items:[{name:'Full',m3u8:'https://media.example/a.m3u8'},{name:'Trailer',m3u8:'https://media.example/trailer.m3u8'},{name:'Full',embed:'https://media.example/player'},{name:'Full',m3u8:'javascript:alert(1)'},{name:'Full',m3u8:'https://media.example/a.m3u8'}]}]};
const meta={id:'tt123',name:'Fixture',releaseInfo:'2025',country:'Vietnam'};
assert(s.remember(movie,meta,'movie'));
const record=s.snapshot()['movie:tt123'][0];
assert.equal(s.streamsFor(movie,parseRequest('movie','tt123'),record).length,1);
assert(!s.remember(movie,{...meta,releaseInfo:'2024'},'movie'));
assert(!s.remember(movie,{...meta,name:'Different'},'movie'));
const foreign={...movie,category:{...category,country:{group:{name:'Quốc gia'},list:[{name:'Âu Mỹ'}]}}};
assert(!s.remember(foreign,meta,'movie'));
assert.deepEqual(s.streamsFor(foreign,parseRequest('movie','tt123'),record),[]);
const series={...movie,slug:'fixture-series',name:'Fixture Season 2',category:{...category,type:{group:{name:'Định dạng'},list:[{name:'Phim bộ'}]}},episodes:[{server_name:'Vietsub',items:[{name:'Tập 01',m3u8:'https://media.example/1.m3u8'},{name:'Tập 10',m3u8:'https://media.example/10.m3u8'},{name:'1-2',m3u8:'https://media.example/combined.m3u8'}]}]};
assert(s.remember(series,{...meta,id:'tt456',name:'Fixture Season 2'},'series'));
const sr=s.snapshot()['series:tt456'][0];
assert.equal(s.streamsFor(series,parseRequest('series','tt456:2:1'),sr)[0].url,'https://media.example/1.m3u8');
assert.deepEqual(s.streamsFor(series,parseRequest('series','tt456:1:1'),sr),[]);
assert.deepEqual(s.streamsFor(series,parseRequest('series','tt456:2:2'),sr),[]);
assert.equal(s.seasonOf({...series,name:'Fixture',original_name:'Fixture'}),null);
s.restore({'movie:tt999':[{...record,slug:'../bad'}]});assert(!s.snapshot()['movie:tt999']);
const snapshot=s.snapshot();s.restore(snapshot);assert.deepEqual(s.snapshot(),snapshot);
(async()=>{
 let merged=[];
 global.fetch=async url=>({ok:true,status:200,headers:{get:()=> 'application/json'},json:async()=>url.includes('/api/film/')?{status:'success',movie}:{status:'success',items:[movie]}});
 const result=await s.refresh({mapTitle:async()=>({...meta,type:'movie'}),meta:async()=>meta,isAsian:()=>true,isVietnam:()=>true,merge:(key,a)=>{merged.push({key,a});return a.length},mapLimit:async(a,n,fn)=>Promise.all(a.map(fn))});
 assert.equal(result.added,1);assert.equal(merged.find(x=>x.key==='vnMovie').a.length,1);
 assert.equal((await s.streams('movie','tt123',async()=>meta)).length,1);
 const blocked={...movie,slug:'blocked-fixture'};s.remember(blocked,{...meta,id:'tt789'},'movie');
 const beforeBlocked=s.snapshot();
 let calls=0;
 global.fetch=async()=>{calls++;return {ok:false,status:403}};
 assert.deepEqual(await s.streams('movie','tt789',async()=>meta),[]);
 assert.match(s.health().lastStream,/403/);
 await assert.rejects(()=>s.refresh({}),/403/);
 assert.equal(calls,1,'403 cooldown prevents repeated upstream calls');
 assert.deepEqual(s.snapshot(),beforeBlocked,'blocked source retains existing mappings');
 console.log('PASS NguonC region, exact title/year, season, exact episode, HLS-only, deduplication, persistence, 403 isolation/cooldown');
})().catch(e=>{console.error(e);process.exitCode=1});
